export const cardData = [
  {
    id: "1",
    title: "GST Preparation Services",
    content: "Services related to Goods and Service Tax where you get professional assistance to prepare monthly or quarterly returns. Approximately 30+ professional services related to GST.",
    subtitle: "Subtitle 1",
    image: "/cardImage/GST.png",
  },
  {
    id: "2",
    title: "Income Tax Returns",
    content: "Services related to Income Tax where you get professional assistance to prepare tax returns for salaried/business (ITR 1 to 5. Approximately 10+ professional services associated with ITR.",
    subtitle: "Subtitle 2",
    image: "/cardImage/ITR.png",
  },
  {
    id: "3",
    title: "Digital Signature (DSC)",
    content: "DSC – Class 3 – Only Signing & Signing + Encryption \n DSC – Class 3 DGFT ",
    subtitle: "Subtitle 3",
    image: "/cardImage/DSC.png",
  },
  {
    id: "4",
    title: "Company Formation Services with MCA",
    content: "Udyam, FSSAI, Shop & Establishment, LLP, OPC, Nidhi, Private Limited Company Preparation & Professional Services. Total 20+ services",
    subtitle: "Subtitle 4",
    image: "/cardImage/CFS.png",
  },
  {
    id: "5",
    title: "Accounting Services",
    content: "Monthly/Yearly Accounting Professional Services. More than 10+ services.",
    subtitle: "Subtitle 5",
    image: "/cardImage/AC.png",
  },
  {
    id: "6",
    title: "Other Services Related to Tax/ Company/Accounting",
    content: "Total 130+ Services",
    subtitle: "Subtitle 6",
    image: "/cardImage/otherITR.png",
  },
  {
    id: "7",
    title: "Loans",
    content: "Personal Loan, Business Loan, Housing Loan, Loan Against Property, MSME Loan, Peer To Peer Lending / Micro Finance",
    subtitle: "Subtitle 6",
    image: "/cardImage/Loan.png",
  },
  {
    id: "8",
    title: "Insurance",
    content: "Health Insurance, Vehicle / Motor Insurance, Travel Insurance, Corporate Insurance, Personal Accident, Group Term Insurance, Life Insurance, Keyman Insurance, Commercial Vehcile Insurance",
    subtitle: "Subtitle 6",
    image: "/cardImage/Insurance.png",
  },
  {
    id: "9",
    title: "Tour And Travel Services",
    content: "Flight Tickets, Holiday Packages, Hotel Bookings, IRCTC – Railway Ticket Booking ( IRCTC License Fees Applicable)",
    subtitle: "Subtitle 6",
    image: "/cardImage/tats.png",
  },
  {
    id: "10",
    title: "Website & Graphic Package Design License",
    content: "1 Page Website + Domain + Hosting + 1 Business Email + Logo, E-Commerce Website + Domain + Hosting + 1 Business Email + Logo + 20 Pages, SSL ( Security for Websites), Logo Design, Brochure (1 Page), Pamphlet, Listing in 10 Local Websites, City Wise SEO Promotion, Google Ads Set-Up - One-time, Facebook Ads Set-Up - One Time, Social Media Pages Creation",
    subtitle: "Subtitle 6",
    image: "/cardImage/graphics1.png",
  },
  {
    id: "11",
    title: "Micro ATM Service",
    content: "Sale By Card ( Debit Card / Credit Card ), Sale by Cash, UPI Payment, DMT ( Domestic Money Transfer), AEPS ( Aadhaar Enabled Payment System), Micro Atm,( Hardware Fees Applicable)",
    subtitle: "Subtitle 6",
    image: "/cardImage/atm.png",
  },
  {
    id: "12",
    title: "Recharges",
    content: "Pre-paid Recharge, DTH Recharge, Data Card Recharge",
    subtitle: "Subtitle 6",
    image: "/cardImage/recharge.png",
  },
  {
    id: "13",
    title: "Bill Payment",
    content: "Water, Mobile, Gas, Electricity, Landline, Internet, Data Card, Cable TV, DTH, Insurance Premium",
    subtitle: "Subtitle 6",
    image: "/cardImage/bills.png",
  },
];